// src/i18n.ts
export type Lang = 'en' | 'zh'

const dict = {
  // Navigation
  upload: { en: 'Upload', zh: '上传' },
  analyze: { en: 'Analyze', zh: '开始分析' },
  uploadMore: { en: 'Upload More', zh: '继续上传' },

  // Tabs
  overview: { en: 'Overview', zh: '总览' },
  positions: { en: 'Positions', zh: '持仓' },
  trades: { en: 'Trades', zh: '交易记录' },

  // Overview cards
  totalNav: { en: 'Total NAV', zh: '账户总市值' },
  totalPL: { en: 'Total P/L', zh: '总盈亏' },
  totalReturn: { en: 'Net Return', zh: '净投资收益率' },
  twr: { en: 'Time-Weighted Return', zh: '时间加权收益率' },

  // Positions table
  ticker: { en: 'Ticker', zh: '股票' },
  qty: { en: 'Qty', zh: '数量' },
  costPrice: { en: 'Cost Price', zh: '成本价' },
  currentPrice: { en: 'Current Price', zh: '当前价' },
  marketValue: { en: 'Market Value', zh: '市值' },
  realizedPL: { en: 'Realized P/L', zh: '已实现盈亏' },
  unrealizedPL: { en: 'Unrealized P/L', zh: '未实现盈亏' },
  returnPct: { en: 'Return %', zh: '收益率' },
  action: { en: 'Action', zh: '操作' },
  share: { en: 'Share', zh: '分享' },

  // Trades table
  date: { en: 'Date', zh: '日期' },
  side: { en: 'Side', zh: '方向' },
  buy: { en: 'Buy', zh: '买入' },
  sell: { en: 'Sell', zh: '卖出' },
  price: { en: 'Price', zh: '成交价' },
  proceeds: { en: 'Proceeds', zh: '金额' },
  commission: { en: 'Commission', zh: '手续费' },

  // Share card
  totalReturnCard: { en: 'Total Return', zh: '累计收益率' },
  totalPLCard: { en: 'Total P/L', zh: '累计盈亏' },
  realized: { en: 'Realized', zh: '已实现' },
  unrealized: { en: 'Unrealized', zh: '未实现' },
  mktValue: { en: 'Mkt Value', zh: '总市值' },
  cost: { en: 'Cost', zh: '成本价' },
  generatedBy: {
    en: 'Generated by IBKR Modern Statements',
    zh: '由 IBKR Modern Statements 生成',
  },

  // Upload page
  dragDrop: {
    en: 'Drag & drop IBKR CSV files here, or click to browse',
    zh: '拖拽 IBKR CSV 文件到此处，或点击选择',
  },
  overlapDetected: {
    en: 'Overlap detected — deduplicating',
    zh: '检测到日期重叠 — 自动去重',
  },
  howToExport: { en: 'How to export from IBKR', zh: '如何从 IBKR 导出报表' },
  period: { en: 'Period', zh: '期间' },
  remove: { en: 'Remove', zh: '删除' },
  account: { en: 'Account', zh: '账户' },
  currency: { en: 'Currency', zh: '货币' },
  tryDemo: { en: 'Try Demo', zh: '体验 Demo' },
  demoLabel: { en: 'DEMO', zh: 'DEMO' },
  maskValues: { en: 'Hide $', zh: '隐藏金额' },
  unmaskValues: { en: 'Show $', zh: '显示金额' },
  exportStep1: {
    en: 'Log in to IBKR → Reports → Statements',
    zh: '登录 IBKR → 报告 → 报表',
  },
  exportStep2: {
    en: 'Select Activity statement type',
    zh: '选择"活动"报表类型',
  },
  exportStep3: {
    en: 'Choose date range (max 365 days) → CSV forma in English',
    zh: '选择日期范围（最长 365 天）→ CSV 格式（选择英文导出）',
  },
  exportStep4: {
    en: 'Download and upload here. For longer history, export multiple CSVs.',
    zh: '下载后上传到此处。历史更长时可导出多个 CSV。',
  },

  // Privacy notice
  privacyNotice: {
    en: '🔒 All processing happens locally in your browser — no data is ever uploaded to any server.',
    zh: '🔒 所有操作均在本地浏览器完成，您的数据不会上传至任何服务器。',
  },
} as const

type DictKey = keyof typeof dict

export function createT(lang: Lang) {
  return (key: DictKey): string => dict[key][lang]
}
